### ISSUE TITLE
Feature request: a way to display the config file location

### ISSUE THREAD

**Issue by neutrinoceros** [dlvhdr/gh-dash#82] opened 2022-02-09 09:24 UTC
**Is your feature request related to a problem? Please describe.**
I've been trying to update my configuration file in `~/.config/prs/config.yml` but I keep falling back to the default configuration.
I can't tell if it's loading a configuration from somewhere else or if my config file is somehow invalid. I'd be in a much better place if only the application gave me more insight.

**Describe the solution you'd like**
- In case the configuration is invalid, display an error message (and possibly quit).
- add an option (in the help menu ?) to print the file path from which configuration was loaded.

**Describe alternatives you've considered**
The configuration path could be always visible ?

**Additional context**

**Comment by dlvhdr** [comment] 2022-02-09 10:02
Thanks @neutrinoceros, that's a good idea.
I also want to add a hotkey to open the config file with vim or something.

**Comment by gennaro-tedesco** [comment] 2022-02-15 22:32
I too am seeing the same problem, namely the configuration file is being ignored. The [README](https://github.com/dlvhdr/gh-prs#configuring) states that 

> under the extension's directory (usually ~/.config/prs/)

however, the extension's directory is usually `$HOME/.local/share/gh/extensions`, is it not? This said, I tried to create the `config.yaml` both in `$HOME/.local/share/gh/extensions` and in `$HOME/.config/prs` (a directory that I had to create myself) to no avail. 

## Solution

By looking at [the config source code](https://github.com/dlvhdr/gh-prs/blob/f67d92bccfb9fa7187acea2a15019dce1ad0f9ea/config/parser.go#L121) we explicitly call the environment variable `XDG_CONFIG_HOME`, and the problem is that if such environment variable is not explicitly set such configuration is ignored. By explicitly exporting it then my configs are indeed taken into account.

**Comment by neutrinoceros** [comment] 2022-02-16 06:51
> On most computers XDG_CONFIG_HOME defaults to ~/.config even without being explicitly set, I presume this is the source of misunderstanding (especially on MacOs I believe).

Good call, I am on MacOs indeed.

**Comment by TonioGela** [comment] 2022-04-01 23:13
> > On most computers XDG_CONFIG_HOME defaults to ~/.config even without being explicitly set, I presume this is the source of misunderstanding (especially on MacOs I believe).
> 
> Good call, I am on MacOs indeed.

I just discovered he uses `os.UserConfigDir()` that on MacOsX points to `$HOME/Library/Application Support/`, so search there for gh-dash.

@dlvhdr I suggest you to change the default location in Darwin to `$HOME/.config` too

**Comment by hallaji** [comment] 2022-04-03 02:45
> @dlvhdr I suggest you to change the default location in Darwin to `$HOME/.config` too

I had similar issue. I found the default config file under `$HOME/Library/Application Support/` which is mostly for system and third-party apps. I think it would be great having `$HOME/.config` as the default location for Unix-like OS.

**Comment by dlvhdr** [comment] 2022-05-28 12:04
Fixed in #135

**Closed** 2022-05-28 12:04 UTC

**Comment by neutrinoceros** [comment] 2022-05-28 12:37
thank you very much !
