### ISSUE TITLE
Support android-arm64

### ISSUE THREAD

**Issue by exatonix** [dlvhdr/gh-dash#341] opened 2024-02-26 09:38 UTC
not support by arm64 says in termux (Redmi Note 10S A13 Tiramisu Lineage OS 18 Based Custom Crdroid 9.2 ROM (Root/Unroot)

**Comment by exatonix** [comment] 2024-02-26 09:40
not support by arm64 says in termux (Redmi Note 10S A13 Tiramisu Lineage OS 18 Based Custom Crdroid 9.2 ROM (Root/Unroot)

**Comment by HyperAfnan** [comment] 2024-05-31 18:36
Duplicate of #304

**Closed** 2024-05-31 18:50 UTC
